development:
  adapter: sqlite3
  encoding: unicode
  database: devdb
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  encoding: unicode
  database: testdb
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  encoding: unicode
  database: productiondb
  pool: 5
  timeout: 5000
